### ISSUE TITLE
"Failed to retrieve valid WikiWho data"

### ISSUE THREAD

**Issue by TS404** [wikiwho/WhoColor#10]
As of 26 Nov 2017, WhoColor script (using tampermonkey) fails to load, with error report:

"Failed to retrieve valid WikiWho data"

Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by faflo** [comment]
Hi, it works for me, and the API is operating fine as well, for all 4 languages. Can you give more details? Is this the first time you are using the userscript? Is it the latest version? You can get the latest one here: https://github.com/wikiwho/WhoColor/raw/master/userscript/whocolor.user.js

**Comment by TS404** [comment]
Aha, thank you. I was using an old version of the script (whoCOLOR 1.02 rather than WhoColor 1.1). It had been working fine for the last six months, but just noticed the error.

The v1.1 works totally fine now, except that the annotations no longer show up when I print to PDF. Is there's a workaround for saving the annotated page?

**Comment by faflo** [comment]
Currently not, I would try a screenshot add-on like "Awesome Screenshot" or the like. Let me know if that worked.
