### ISSUE TITLE
Incomplete response for very large page

### ISSUE THREAD

**Issue by ragesoss** [wikiwho/WhoColor#20]
The tools that use the whocolor API, both the 'Who Wrote That' script that the Wikimedia community tech team developed and the Authorship Highlighting feature of dashboard.wikiedu.org, are not working with this page: https://en.wikipedia.org/wiki/COVID-19_pandemic_in_the_United_States

Here's the API call: https://api.wikiwho.net/en/whocolor/v1.0.0-beta/COVID-19 pandemic in the United States/?origin=*

It looks like the whocolor API cuts off the response before it's complete, after about 9.5 MB of data.

**Comment by faflo** [comment]
The response to the call seems now complete, can you check again? (There is still erroneous parsing of references and templates going on, but at least the answer should not be cut off anymore)

**Comment by ragesoss** [comment]
I'm still getting invalid JSON from [this request]( https://api.wikiwho.net/en/whocolor/v1.0.0-beta/COVID-19 pandemic in the United States/?origin=*). The response body is 9.64 megabytes, but it throws an unterminated string error trying to parse it with JSON.parse.

**Comment by wikiwho** [comment]
We cannot reproduce the error. 

Could you see if this works for you? If not, what is the error?

import requests
S = requests.Session()
URL = "https://api.wikiwho.net/en/whocolor/v1.0.0-beta/COVID-19%20pandemic%20in%20the%20United%20States"

PARAMS_0 = {
    'origin':"*",
}

R = S.get(url=URL, params=PARAMS_0)
DATA = R.json()

########
#get  text of response

import json
y = json.loads(R.text)

**Comment by ragesoss** [comment]
Thanks!

After poking around more, I believe the error I referred to is an artifact of the Firefox dev tools; the Response viewer automatically cuts off large responses, and then shows a misleading error message when it tries to parse and display a very large JSON response. Sorry about that!

What I was seeing previously — malformed HTML — was probably actually from the mis-parsed templates you referred to. The latest version of the page doesn't have that problem, probably because of some significant content reorganization — moving big sections to subarticles — that's been going on recently. Both the dashboard.wikiedu.org authorship highlighting and the Who Wrote That extension seems to be working properly on that article now.
