### ISSUE TITLE
Cannot fetch whocolor data via Javascript due to access control

### ISSUE THREAD

**Issue by ragesoss** [wikiwho/WhoColor#4]
I'm trying to update Wiki Education Dashboard to use the beta endpoint, but I'm stuck with security issues: I can't make the cross-domain requests. For example, I get this:

```
XMLHttpRequest cannot load https://api.wikiwho.net/whocolor/v1.0.0-beta/Nancy%20Tuana/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

(It won't work as a jsonp request either, because the mime type returned is `json`.)

**Comment by bitnik** [comment]
hey @ragesoss, sorry for the problem. i fixed it, now it should work.

**Comment by ragesoss** [comment]
Confirmed, thanks!
